version: '3'
services:
    study-golang:
        build: 
            context: ./golang/centos
            dockerfile: Dockerfile
        container_name: study-golang
        hostname: study-golang
        networks: 
            webserver:
                ipv4_address: 172.52.1.2
        # ports:
        #     - "8080:8080"
        #     - "8081:8081"
        #     - "8082:8082"
        #     - "8083:8083"
        volumes: 
            - "./server:/wwwroot/server"
        tty: true
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        hostname: nginx
        networks: 
            webserver:
                ipv4_address: 172.52.1.3
        ports:
            - "82:82"
            - "83:83"
            - "84:84"
            - "85:85"
            - "86:86"
            - "87:87"
            - "88:88"
            - "89:89"
        # depends_on:
        #     - golang
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx/conf:/etc/nginx/conf"
            - "./nginx/html:/etc/nginx/html"
            - "./nginx/static:/etc/nginx/static"
networks: 
    webserver:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: "172.52.1.0/24"